# Autogenerated wrapper script for libgifextra_jll for i686-w64-mingw32
export libgifextra

using Giflib_jll
JLLWrappers.@generate_wrapper_header("libgifextra")
JLLWrappers.@declare_library_product(libgifextra, "libgifextra.dll")
function __init__()
    JLLWrappers.@generate_init_header(Giflib_jll)
    JLLWrappers.@init_library_product(
        libgifextra,
        "bin\\libgifextra.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
